----SQL RETAIL SALES ANALYSIS----
CREATE DATABASE RETAIL

--DROP TABLE IF EXISTS RETAIL_SALES--

----DROP TABLE RETAIL_SALES 

CREATE TABLE RETAIL_SALES(
transactions_id	INT PRIMARY KEY,
sale_date DATE,
sale_time TIME,
customer_id	INTEGER,
gender VARCHAR(15),
age	INTEGER,
category VARCHAR(15),	
quantiy INTEGER,
price_per_unit FLOAT,
cogs FLOAT,	
total_sale FLOAT
);

SELECT * FROM RETAIL_SALES
WHERE 
transactions_id IS NULL
OR
sale_date IS NULL
OR
sale_time IS NULL
OR
customer_id IS NULL
OR
gender IS NULL
OR
age IS NULL
OR
category IS NULL
OR
quantiy IS NULL
OR
price_per_unit IS NULL
OR
cogs IS NULL
OR
total_sale IS NULL;

select count(*) from retail_sales
---DATA CLEANING---
DELETE FROM RETAIL_SALES
WHERE 
transactions_id IS NULL
OR
sale_date IS NULL
OR
sale_time IS NULL
OR
customer_id IS NULL
OR
gender IS NULL
OR
age IS NULL
OR
category IS NULL
OR
quantiy IS NULL
OR
price_per_unit IS NULL
OR
cogs IS NULL
OR
total_sale IS NULL;

SELECT * FROM RETAIL_SALES;

----DATA EXPLORATION----
--HOW MAN SALES WE HAVE?---
SELECT COUNT(*) FROM RETAIL_SALES
---HOW MANY UNIQUE CUSTOMERS WE HAVE ?
SELECT COUNT(DISTINCT(CUSTOMER_ID)) FROM RETAIL_SALES

SELECT DISTINCT CATEGORY FROM RETAIL_SALES
--DATA ANALYSIS--
--1. SQL QUERY FOR SALES MADE ON 2022-11-05---
SELECT TRANSACTIONS_ID, SALE_DATE, TOTAL_SALE FROM RETAIL_SALES
WHERE SALE_DATE = '2022-11-05'

--- TRANSACTIONS FOR THE CATEGORY CLOTHING AND QUANTITY SOLD MORE THAN 4 
--IN THE MONTH OF NOV-2022

SELECT * FROM RETAIL_SALES
WHERE CATEGORY = 'Clothing' and to_char(sale_date,'yyyy-mm')= '2022-11'
and quantiy >= 4

--total sales for each category--
SELECT CATEGORY, SUM(TOTAL_SALE) AS NETSALES, COUNT(*) AS TOTALORDERS
FROM RETAIL_SALES
GROUP BY CATEGORY 

--AVERAGE AGE OF ITEMS WHO PURCHASED ITEMS FROM BEAUTY CAEGORY--
SELECT CATEGORY, ROUND(AVG(AGE),2) AS AVG_AGE
FROM RETAIL_SALES
where category = 'Beauty'
group by category

--- TRANSACTIONS WHERE TOTAL SALES MORE THAN 1000'
SELECT * FROM RETAIL_SALES
WHERE TOTAL_SALE> 1000
ORDER BY TOTAL_SALE DESC

--TOTAL NO O TRANSACTIONS BY GENDER IN EACH CATEGORY--
SELECT GENDER, CATEGORY, COUNT(*) AS TOTALTRANS
FROM RETAIL_SALES
GROUP BY GENDER , CATEGORY
ORDER BY CATEGORY

SELECT * FROM RETAIL_SALES
--AVERAGE SALE FOR EACH MONTH AND FIND THE BEST SELLING MONTH IN EACH YEAR

SELECT * FROM
(SELECT EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
EXTRACT(MONTH FROM SALE_DATE) AS MONTH, ROUND(AVG(TOTAL_SALE)) AS TOTALSALE,
RANK() OVER(PARTITION BY EXTRACT(YEAR FROM SALE_DATE) ORDER BY AVG(TOTAL_SALE) DESC) AS RANK
FROM RETAIL_SALES
GROUP BY YEAR, MONTH) AS T1
WHERE RANK = 1
--ORDER BY YEAR,TOTALSALE DESC

--TOP 5 CUSTOMERS WITH HIGHEST TOTAL SALES
SELECT customer_id, SUM(total_sale) AS TOTALSALES
from retail_sales
GROUP BY customer_id
ORDER BY TOTALSALES DESC
LIMIT 5

--9 UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY
SELECT CATEGORY, COUNT(DISTINCT(CUSTOMER_ID)) AS UCUST
FROM RETAIL_SALES
GROUP BY CATEGORY
ORDER BY CATEGORY

--10 NO OF ORDERS BETWEEN SHIFTS

WITH HOURLY_SALE AS 
(SELECT *,
	CASE 
		WHEN EXTRACT(HOUR FROM SALE_TIME)<12 THEN 'MORNING' 
		WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
		ELSE 'EVENING'
	END AS SHIFT
FROM RETAIL_SALES)
SELECT SHIFT,COUNT(*) AS TOTAL_ORDERS
FROM HOURLY_SALE
GROUP BY SHIFT

---end of project----

































